name = "MultiScales"
uuid = "d24ad848-1d7e-4ebf-9da3-2ede15b5f46e"
authors = ["Hiroshi Shinaoka <h.shinaoka@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
NDTensors = "23ae76d9-e61a-49c4-8f12-3f1a16adf9cf"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseIR = "4fe2279e-80f0-4adb-8463-ee114ff56b7d"

[compat]
ITensors = "0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
